#!/usr/bin/env python
"""Generate `models.lock` from the routing registry — the pinned set of hosted model ids.

Usage:  uv run python scripts/write_models_lock.py  [--check]

`--check` verifies the committed lock matches the registry (for CI drift detection) and exits
non-zero on mismatch instead of writing.
"""

from __future__ import annotations

import sys
from pathlib import Path

from api.providers import registry
from api.providers.base import Role

LOCK_PATH = Path(__file__).resolve().parents[1] / "models.lock"

HEADER = """\
# models.lock — pinned hosted model ids used by the LLM routing registry.
# GENERATED by scripts/write_models_lock.py from api.providers.registry — do not edit by hand
# (run `make models-lock`).
#
# NOTE: hosted model ids can drift or be deprecated server-side. This file pins the *intended*
# ids only; the eval harness (M8) is the monitor of record for behavioural regressions.
"""


def render() -> str:
    lines = [HEADER]
    for profile in ("balanced", "quality-max"):
        lines.append(f"[{profile}]")
        for model in sorted(registry.all_models(profile)):
            lines.append(model)
        lines.append("")
        lines.append(f"# {profile} role routing:")
        for role in Role:
            spec = registry.resolve(role, profile)
            detail = f"effort={spec.effort}" if spec.supports_effort else f"temp={spec.temperature}"
            lines.append(f"#   {role.value:12s} -> {spec.model} ({detail})")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    content = render()
    if "--check" in argv:
        current = LOCK_PATH.read_text() if LOCK_PATH.exists() else ""
        if current != content:
            print("models.lock is out of date; run `make models-lock`", file=sys.stderr)
            return 1
        print("models.lock is up to date.")
        return 0
    LOCK_PATH.write_text(content)
    print(f"wrote {LOCK_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
