"""M7(a) — SEC-shaped Form 13F information-table draft + reviewer CSV, from HOLDS edges.

Value comes from HOLDS.value_usd; CUSIP + SEC issuer name from the committed
`fixtures/cusip_crosswalk.csv`. The output carries a DRAFT watermark and is NOT a filing: the
seed graph has no share counts, so `sshPrnamt`/voting are 0 and every such row is flagged in the
reviewer CSV. The XML is rendered deterministically (stable ordering + fixed formatting) so it can
be golden-file tested against `fixtures/golden/13f_<fund>.xml`.
"""

from __future__ import annotations

import csv
import io
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

_ROOT = Path(__file__).resolve().parents[3]
CROSSWALK_PATH = _ROOT / "fixtures" / "cusip_crosswalk.csv"
GOLDEN_DIR = _ROOT / "fixtures" / "golden"

INFOTABLE_NS = "http://www.sec.gov/edgar/document/thirteenf/informationtable"
DRAFT_NOTE = (
    "DRAFT - generated by Firm Ontology Platform POC from N-PORT-derived HOLDS edges; "
    "NOT FOR FILING. Share counts and voting authority are absent from the source and require "
    "reviewer input (see the accompanying reviewer CSV)."
)

# Fund -> short slug used for golden filenames.
FUND_SLUG = {
    "Demo Growth Fund": "growth",
    "Demo Focused Growth Fund": "focused",
}

HOLDINGS_CYPHER = (
    "MATCH (f:Fund {name:$fund})-[h:HOLDS]->(co:Company)\n"
    "RETURN co.name AS company, co.ticker AS ticker, co.cik AS cik,\n"
    "       h.value_usd AS value_usd, h.shares AS shares, h.as_of AS as_of\n"
    "ORDER BY h.value_usd DESC, co.name"
)


def fund_slug(fund: str) -> str:
    if fund in FUND_SLUG:
        return FUND_SLUG[fund]
    return "".join(c.lower() if c.isalnum() else "_" for c in fund).strip("_")


def golden_path(fund: str) -> Path:
    return GOLDEN_DIR / f"13f_{fund_slug(fund)}.xml"


def load_crosswalk(path: Path = CROSSWALK_PATH) -> dict[str, dict]:
    """ticker -> {cusip, issuer_name, title_of_class}."""
    out: dict[str, dict] = {}
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            out[row["ticker"]] = {
                "cusip": row["cusip"],
                "issuer_name": row["issuer_name"],
                "title_of_class": row["title_of_class"],
            }
    return out


def _entry(h: dict, crosswalk: dict[str, dict]) -> dict:
    ticker = h.get("ticker")
    cw = crosswalk.get(ticker) if ticker else None
    flags: list[str] = []
    if cw is None:
        flags.append("NO_CUSIP")
    if h.get("value_usd") is None:
        flags.append("MISSING_VALUE")
    if h.get("shares") is None:
        flags.append("MISSING_SHARES")
    value = int(round(float(h["value_usd"]))) if h.get("value_usd") is not None else 0
    shares = int(h["shares"]) if h.get("shares") is not None else 0
    return {
        "company": h["company"],
        "ticker": ticker,
        "name_of_issuer": cw["issuer_name"] if cw else (h["company"] or "").upper(),
        "title_of_class": cw["title_of_class"] if cw else "COM",
        "cusip": cw["cusip"] if cw else "",
        "value": value,
        "ssh_prnamt": shares,
        "investment_discretion": "SOLE",
        "voting_sole": shares,
        "flags": flags,
    }


def build_entries(holdings: list[dict], crosswalk: dict[str, dict] | None = None) -> list[dict]:
    crosswalk = crosswalk if crosswalk is not None else load_crosswalk()
    entries = [_entry(h, crosswalk) for h in holdings]
    entries.sort(key=lambda e: (-e["value"], e["name_of_issuer"], e["cusip"]))
    return entries


def render_info_table_xml(entries: list[dict]) -> str:
    """Render the deterministic SEC-shaped informationTable XML (with DRAFT watermark)."""
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f"<!-- {DRAFT_NOTE} -->",
        f'<informationTable xmlns="{INFOTABLE_NS}">',
    ]
    for e in entries:
        lines += [
            "  <infoTable>",
            f"    <nameOfIssuer>{escape(e['name_of_issuer'])}</nameOfIssuer>",
            f"    <titleOfClass>{escape(e['title_of_class'])}</titleOfClass>",
            f"    <cusip>{escape(e['cusip'])}</cusip>",
            f"    <value>{e['value']}</value>",
            "    <shrsOrPrnAmt>",
            f"      <sshPrnamt>{e['ssh_prnamt']}</sshPrnamt>",
            "      <sshPrnamtType>SH</sshPrnamtType>",
            "    </shrsOrPrnAmt>",
            f"    <investmentDiscretion>{e['investment_discretion']}</investmentDiscretion>",
            "    <votingAuthority>",
            f"      <Sole>{e['voting_sole']}</Sole>",
            "      <Shared>0</Shared>",
            "      <None>0</None>",
            "    </votingAuthority>",
            "  </infoTable>",
        ]
    lines.append("</informationTable>")
    return "\n".join(lines) + "\n"


def render_reviewer_csv(entries: list[dict]) -> str:
    """Reviewer worksheet: one row per holding + a flags column for missing/needs-review data."""
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow(
        ["nameOfIssuer", "titleOfClass", "cusip", "value_usd", "sshPrnamt",
         "investmentDiscretion", "votingSole", "ticker", "flags"]
    )
    for e in entries:
        writer.writerow(
            [e["name_of_issuer"], e["title_of_class"], e["cusip"], e["value"], e["ssh_prnamt"],
             e["investment_discretion"], e["voting_sole"], e["ticker"] or "",
             ";".join(e["flags"])]
        )
    return buf.getvalue()


def build_13f(fund: str, holdings: list[dict], crosswalk: dict[str, dict] | None = None) -> dict:
    """Full 13F draft for a fund from HOLDS rows: {xml, reviewer_csv, entries, totals}."""
    entries = build_entries(holdings, crosswalk)
    total_value = sum(e["value"] for e in entries)
    return {
        "fund": fund,
        "slug": fund_slug(fund),
        "xml": render_info_table_xml(entries),
        "reviewer_csv": render_reviewer_csv(entries),
        "entries": entries,
        "totals": {"n_holdings": len(entries), "total_value_usd": total_value},
        "cypher": HOLDINGS_CYPHER,
    }


def build_13f_from_graph(run: Any, fund: str, crosswalk: dict[str, dict] | None = None) -> dict:
    """Fetch HOLDS rows from the live graph and build the 13F draft."""
    exec_ = run.run if hasattr(run, "run") else run
    holdings = exec_(HOLDINGS_CYPHER, fund=fund)
    return build_13f(fund, holdings, crosswalk)
